### ISSUE TITLE
Why a split package?

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/mediainfo#1]
Seems a bit odd to do all the work to split out the libs, but then the only package that needs those libs is exactly the same you split them from......

**Comment by JantarMantar** [comment]
Thanks for the suggestion. You are right, mediainfo is the only package that uses these libs. I copied these PKGBUILDs from Arch and kept almost unchanged primarily because I don't have much of development background to fully understand how packages are build. If you a have a suggestion on building this package in a more concise way that you describe, please do share. I am sure it'll be a good learning opportunity.

**Comment by JantarMantar** [comment]
Merged libzen and libmediainfo into this package. Hopefully, this will make it easier to install this package without needing to install dependencies separately. Separate entries for libzen and libmediainfo will be removed from kcp.
